spring:
  profiles:
    default: ho-so_chi-tiet
    active: ho-so_chi-tiet
  application:
    name: ho-so_chi-tiet #name application in eureka
  config:
    import: optional:configserver:http://localhost:1111

