spring:
  application:
    name: tai-khoan #name application in eureka
  config:
    import: optional:configserver:http://localhost:1111

gateway-port:
  tai-khoan: https://8888-giaptai-microservicehrm-9gkik3hfxs2.ws-us110.gitpod.io/api/v1


