spring:
  profiles:
    default: tai-khoan
    active: gitpod_pho
  application:
    name: tai-khoan #name application in eureka
  config:
    import: optional:configserver:http://localhost:1111

gateway-port:
  tai-khoan: https://8888-giaptai-microservicehrm-dhv6yvngrm5.ws-us110.gitpod.io/api/v1


