spring:
  profiles:
    default: cau-hinh2 #name profiles
  application: #this must same name at yml file in config-server
    name: cau--hinh
  config:
    import: optional:configserver:http://localhost:1111


