spring:
  application: #this must same name at yml file in config-server
    name: cau--hinh
  config:
    import: optional:configserver:http://localhost:1111

gateway-port:
  cau-hinh: https://8080-giaptai-microservicehrm-9gkik3hfxs2.ws-us110.gitpod.io/api/v1




