spring:
  profiles:
    default: cau-hinh2 #name profiles
    active: gitpod_pho
  application: #this must same name at yml file in config-server
    name: cau--hinh
  config:
    import: optional:configserver:http://localhost:1111

gateway-port:
  cau-hinh: https://8888-giaptai-microservicehrm-dhv6yvngrm5.ws-us110.gitpod.io/api/v1




