-- nhóm máu
INSERT INTO nhom_mau (name)
values ('A'),
       ('B'),
       ('AB'),
       ('O');
-- doi_tuong_chinh_sach
INSERT INTO doi_tuong_chinh_sach (name)
values ('Không'),
       ('Dân tộc thiểu số'),
       ('Con liệt sĩ');
-- trinh_do_giao_duc_pho_thong
INSERT INTO trinh_do_giao_duc_pho_thong (name)
values ('Không'),
       ('10/10'),
       ('12/12');
-- trinh_do_chuyen_mon
INSERT INTO trinh_do_chuyen_mon (name)
values ('Sơ cấp'),
       ('Trung cấp'),
       ('Cao đẳng'),
       ('Đại học'),
       ('Thạc sĩ'),
       ('Tiến sĩ');
-- học hàm
INSERT INTO hoc_ham (name)
values ('Không'),
       ('Giáo sư'),
       ('Phó giáo sư');
-- danh_hieu_nha_nuoc_phong_tang
INSERT INTO danh_hieu_nha_nuoc (name)
values ('Không'),
       ('Tỉnh Anh hùng'),
       ('Thành phố Anh hùng'),
       ('Bà mẹ Việt Nam Anh hùng'),
       ('Anh hùng Lực lượng vũ trang nhân dân'),
       ('Anh hùng Lao động'),
       ('Nhà giáo nhân dân'),
       ('Nhà giáo ưu tú');
-- dân tộc
INSERT INTO dan_toc (name)
VALUES ("Ba Na"),
       ("Bà Y"),
       ("Bố Y"),
       ("Brau"),
       ("Bru - Vân Kiều"),
       ("Chăm"),
       ("Chơ Ro"),
       ("Chứt"),
       ("Cơ Ho"),
       ("Cơ Tu"),
       ("Cống"),
       ("Coong"),
       ("Cờ Lao"),
       ("Ê Đê"),
       ("Gia Rai"),
       ("Giáy"),
       ("Hà Nhì"),
       ("Hrê"),
       ("Kháng"),
       ("Khơ Mú"),
       ("Khơ Lơ"),
       ("Kinh"),
       ("Krông"),
       ("Lào"),
       ("La Chí"),
       ("La Ha"),
       ("Lô Lô"),
       ("Mảng"),
       ("M'nông"),
       ("Mơ Nông"),
       ("Mường"),
       ("Nùng"),
       ("Ô Đu"),
       ("Pà Thẻn"),
       ("Phù Lá"),
       ("Pu Péo"),
       ("Rơ Măm"),
       ("Ra Glai"),
       ("Rục"),
       ("Sán Chay"),
       ("Sán Dìu"),
       ("Sán Rìu"),
       ("Si La"),
       ("Sơ Rếch"),
       ("Tày"),
       ("Tày Thái"),
       ("Thổ"),
       ("Thái"),
       ("Xinh Mun"),
       ("Xơ Đăng"),
       ("X' Tiêng"),
       ("Ya Chêng"),
       ("Ý Đình"),
       ("Zao");
-- tôn giáo
INSERT INTO ton_giao (name)
VALUES ('Không'),
       ('Phật giáo'),
       ('Công giáo'),
       ('Tin Lành'),
       ('Cao Đài'),
       ('Phật giáo Hòa Hảo'),
       ('Hồi giáo'),
       ('Tôn giáo Baha`i'),
       ('Tịnh độ Cư sỹ Phật hội'),
       ('Cơ đốc Phục lâm'),
       ('Phật giáo Tứ Ân Hiếu nghĩa'),
       ('Minh Sư đạo'),
       ('Ba-la-môn giáo'),
       ('Mặc môn'),
       ('Phật giáo Hiếu Nghĩa Tà Lơn'),
       ('Bửu Sơn Kỳ Hương');
-- thành phần gia đình
insert into thanh_phan_gia_dinh (name)
VALUES ('Cố nông'),
       ('Bần nông'),
       ('Trung nông'),
       ('Phú nông/ Địa chủ'),
       ('Công chức/ Viên chức'),
       ('Nghèo đói'),
       ('Tiểu thương'),
       ('Tiểu chủ'),
       ('Tư sản'),
       ('Tiểu tư sản');
-- bac_luong
INSERT INTO bac_luong (name)
VALUES ('Bậc 1'),
       ('Bậc 2'),
       ('Bậc 3'),
       ('Bậc 4'),
       ('Bậc 5'),
       ('Bậc 6'),
       ('Bậc 7'),
       ('Bậc 8'),
       ('Bậc 9'),
       ('Bậc 10'),
       ('Bậc 11'),
       ('Bậc 12');
-- loai_vien_chuc
INSERT INTO loai_vien_chuc (loai, name)
values ('A3', 'Ngạch viên chức cấp cao'),
       ('A2', 'Ngạch viên chức chính'),
       ('A1', 'Ngạch viên chức'),
       ('A0', 'Ngạch viên chức cán sự'),
       ('B', 'Ngạch nhân viên');
-- loai_cong_chuc
INSERT INTO loai_cong_chuc (loai, name)
values ('A3', 'Chuyên viên cao cấp'),
       ('A2', 'Chuyên viên chính'),
       ('A1', 'Chuyên viên'),
       ('A0', 'Cán sự- Trung cấp'),
       ('B', 'Nhân viên'),
       ('C', 'Khác');
-- nhom_vien_chuc
INSERT into nhom_vien_chuc (name, loai_vien_chuc_id)
values ('A3.1', 1),
       ('A3.2', 1),
       ('A2.1', 2),
       ('A2.2', 2),
       ('A1', 3),
       ('A0', 4),
       ('B', 5);
-- nhom_cong_chuc
INSERT into nhom_cong_chuc (name, loai_cong_chuc_id)
values ('A3.1', 1),
       ('A3.2', 1),
       ('A2.1', 2),
       ('A2.2', 2),
       ('A1', 3),
       ('A0', 4),
       ('B', 5),
       ('C1', 6);
-- he_so_luong_vien_chuc
INSERT into he_so_luong_vien_chuc (nhom_vien_chuc_id, bac_luong_id, he_so)
values (1, 1, 6.2),
       (1, 2, 6.56),
       (1, 3, 6.92),
       (1, 4, 7.28),
       (1, 5, 7.64),
       (1, 6, 8.00),
       (2, 1, 5.75),
       (2, 2, 6.11),
       (2, 3, 6.47),
       (2, 4, 6.83),
       (2, 5, 7.19),
       (2, 6, 7.55),
       (3, 1, 4.4),
       (3, 2, 4.74),
       (3, 3, 5.08),
       (3, 4, 5.42),
       (3, 5, 5.76),
       (3, 6, 6.10),
       (3, 7, 6.44),
       (3, 8, 6.78),
       (4, 1, 4.0),
       (4, 2, 4.34),
       (4, 3, 4.68),
       (4, 4, 5.02),
       (4, 5, 5.36),
       (4, 6, 5.7),
       (4, 7, 6.04),
       (4, 8, 6.38),
       (5, 1, 2.34),
       (5, 2, 2.67),
       (5, 3, 3.00),
       (5, 4, 3.33),
       (5, 5, 3.66),
       (5, 6, 3.99),
       (5, 7, 4.32),
       (5, 8, 4.65),
       (5, 9, 4.98),
       (6, 1, 2.10),
       (6, 2, 2.41),
       (6, 3, 2.72),
       (6, 4, 3.03),
       (6, 5, 3.34),
       (6, 6, 3.65),
       (6, 7, 3.96),
       (6, 8, 4.27),
       (6, 9, 4.58),
       (6, 10, 4.89),
       (7, 1, 1.86),
       (7, 2, 2.06),
       (7, 3, 2.26),
       (7, 4, 2.46),
       (7, 5, 2.66),
       (7, 6, 2.86),
       (7, 7, 3.06),
       (7, 8, 3.26),
       (7, 9, 3.46),
       (7, 10, 3.66),
       (7, 11, 3.86),
       (7, 12, 4.06);
-- he_so_luong_cong_chuc
INSERT into he_so_luong_cong_chuc (nhom_cong_chuc_id, bac_luong_id, he_so)
values (1, 1, 6.2),
       (1, 2, 6.56),
       (1, 3, 6.92),
       (1, 4, 7.28),
       (1, 5, 7.64),
       (1, 6, 8.00),
       (2, 1, 5.75),
       (2, 2, 6.11),
       (2, 3, 6.47),
       (2, 4, 6.83),
       (2, 5, 7.19),
       (2, 6, 7.55),
       (3, 1, 4.4),
       (3, 2, 4.74),
       (3, 3, 5.08),
       (3, 4, 5.42),
       (3, 5, 5.76),
       (3, 6, 6.10),
       (3, 7, 6.44),
       (3, 8, 6.78),
       (4, 1, 4.0),
       (4, 2, 4.34),
       (4, 3, 4.68),
       (4, 4, 5.02),
       (4, 5, 5.36),
       (4, 6, 5.7),
       (4, 7, 6.04),
       (4, 8, 6.38),
       (5, 1, 2.34),
       (5, 2, 2.67),
       (5, 3, 3.00),
       (5, 4, 3.33),
       (5, 5, 3.66),
       (5, 6, 3.99),
       (5, 7, 4.32),
       (5, 8, 4.65),
       (5, 9, 4.98),
       (6, 1, 2.10),
       (6, 2, 2.41),
       (6, 3, 2.72),
       (6, 4, 3.03),
       (6, 5, 3.34),
       (6, 6, 3.65),
       (6, 7, 3.96),
       (6, 8, 4.27),
       (6, 9, 4.58),
       (6, 10, 4.89),
       (7, 1, 1.86),
       (7, 2, 2.06),
       (7, 3, 2.26),
       (7, 4, 2.46),
       (7, 5, 2.66),
       (7, 6, 2.86),
       (7, 7, 3.06),
       (7, 8, 3.26),
       (7, 9, 3.46),
       (7, 10, 3.66),
       (7, 11, 3.86),
       (7, 12, 4.06),
       (8, 1, 1.65),
       (8, 2, 1.83),
       (8, 3, 2.01),
       (8, 4, 2.19),
       (8, 5, 2.37),
       (8, 6, 2.55),
       (8, 7, 2.73),
       (8, 8, 2.91),
       (8, 9, 3.09),
       (8, 10, 3.27),
       (8, 11, 3.45),
       (8, 12, 3.63);
-- hinh_thuc_khen_thuong
INSERT INTO hinh_thuc_khen_thuong(name)
VALUES ('Huân chương'),
       ('Huy chương'),
       ('Danh hiệu vinh dự nhà nước'),
       ('Giải thưởng Hồ Chí Minh'),
       ('Giải thưởng Nhà nước'),
       ('Kỷ niệm chương'),
       ('Bằng khen'),
       ('Giấy khen');
-- chuc_danh_dang
INSERT INTO chuc_danh_dang (name)
VALUES ('Tổng Bí thư'),
       ('Chủ tịch nước'),
       ('Thủ tướng Chính phủ'),
       ('Chủ tịch Quốc hội'),
       ('Thường trực Ban Bí thư'),
       ('Ủy viên Bộ Chính trị'),
       ('Ủy viên Ban Bí thư'),
       ('Chủ tịch Ủy ban Trung ương Mặt trận Tổ quốc Việt Nam'),
       ('Chánh án Toà án nhân dân tối cao'),
       ('Viện trưởng Viện Kiểm sát nhân dân tối cao'),
       ('Phó Chủ tịch nước'),
       ('Phó Thủ tướng Chính phủ'),
       ('Phó Chủ tịch Quốc hội'),
       ('Ủy viên Trung ương Đảng chính thức'),
       ('Trưởng ban, cơ quan đảng ở Trung ương'),
       ('Giám đốc Học viện Chính trị quốc gia Hồ Chí Minh'),
       ('Tổng Biên tập Báo Nhân Dân'),
       ('Tổng Biên tập Tạp chí Cộng sản'),
       ('Ủy viên Ủy ban Thường vụ Quốc hội'),
       ('Bộ trưởng và thủ trưởng cơ quan ngang bộ'),
       ('Chủ nhiệm Văn phòng Chủ tịch nước'),
       ('Tổng Kiểm toán Nhà nước'),
       ('Trưởng tổ chức chính trị - xã hội ở Trung ương'),
       ('Phó Chủ tịch - Tổng Thư ký Ủy ban Trung ương Mặt trận Tổ quốc Việt Nam'),
       ('Bí thư tỉnh ủy, thành ủy, đảng ủy khối trực thuộc Trung ương'),
       ('Phó Bí thư Thành ủy Hà Nội'),
       ('Phó Bí thư Thành ủy Thành phố Hồ Chí Minh'),
       ('Chủ tịch Hội đồng nhân dân, Ủy ban nhân dân thành phố Hà Nội'),
       ('Phó Chủ nhiệm Ủy ban Kiểm tra Trung ương'),
       ('Chủ tịch Viện Hàn lâm Khoa học xã hội Việt Nam'),
       ('Chủ tịch Viện Hàn lâm Khoa học công nghệ Việt Nam'),
       ('Chủ tịch Ủy ban Quản lý vốn nhà nước tại doanh nghiệp'),
       ('Tổng Giám đốc Thông tấn xã Việt Nam'),
       ('Tổng Giám đốc Đài Tiếng nói Việt Nam'),
       ('Tổng Giám đốc Đài Truyền hình Việt Nam'),
       ('Phó trưởng ban, cơ quan đảng ở Trung ương'),
       ('Phó Giám đốc Học viện Chính trị quốc gia Hồ Chí Minh'),
       ('Phó Tổng Biên tập Báo Nhân Dân'),
       ('Phó Tổng Biên tập Tạp chí Cộng sản'),
       ('Phó Chủ tịch Ủy ban Trung ương Mặt trận Tổ quốc Việt Nam'),
       ('Phó Chủ tịch Hội đồng Dân tộc'),
       ('Phó Chủ nhiệm các Ủy ban của Quốc hội'),
       ('Phó Chủ nhiệm Văn phòng Quốc hội'),
       ('Phó Chánh án Toà án nhân dân tối cao'),
       ('Phó Viện trưởng Viện Kiểm sát nhân dân tối cao'),
       ('Thứ trưởng, phó thủ trưởng cơ quan ngang bộ'),
       ('Phó Chủ nhiệm Văn phòng Chủ tịch nước'),
       ('Phó Tổng Kiểm toán Nhà nước'),
       ('Phó trưởng các tổ chức chính trị - xã hội ở Trung ương'),
       ('Bí thư thường trực Trung ương Đoàn Thanh niên Cộng sản Hồ Chí Minh'),
       ('Phó bí thư tỉnh ủy, thành ủy, đảng ủy khối trực thuộc Trung ương'),
       ('Chủ tịch Hội đồng nhân dân, chủ tịch Ủy ban nhân dân tỉnh, thành phố trực thuộc Trung ương'),
       ('Ủy viên Ủy ban Kiểm tra Trung ương'),
       ('Giám đốc Nhà xuất bản Chính trị quốc gia Sự thật'),
       ('Chủ tịch các hội quần chúng do Đảng, Nhà nước giao nhiệm vụ ở Trung ương'),
       ('Trợ lý các đồng chí lãnh đạo chủ chốt của Đảng, Nhà nước');
-- coquan_tochuc_donvi
insert into coquan_tochuc_donvi (name)
VALUES ('Tòa án nhân dân tối cao'),
       ('Viện kiểm sát nhân dân tối cao'),
       ('Kiểm toán Nhà nước'),
       ('Văn phòng Quốc hội'),
       ('Văn phòng Chủ tịch nước'),
       ('Ủy ban nhân dân cấp tỉnh'),
       ('Cơ quan của Đảng Cộng sản Việt Nam'),
       ('Cơ quan trung ương của Mặt trận Tổ quốc Việt Nam');
-- cap_bac_loai_quan_ham_quan_doi
INSERT INTO cap_bac_loai_quan_ham_quan_doi (name)
VALUES ('Đại tướng'),
       ('Thượng tướng'),
       ('Trung tướng'),
       ('Thiếu tướng'),
       ('Đại tá'),
       ('Thượng tá'),
       ('Trung tá'),
       ('Thiếu tá'),
       ('Đại úy'),
       ('Thượng úy'),
       ('Trung úy'),
       ('Thiếu úy'),
       ('Thượng tá quân nhân chuyên nghiệp'),
       ('Trung tá quân nhân chuyên nghiệp'),
       ('Thiếu tá quân nhân chuyên nghiệp'),
       ('Đại úy quân nhân chuyên nghiệp'),
       ('Thượng úy quân nhân chuyên nghiệp'),
       ('Trung úy quân nhân chuyên nghiệp'),
       ('Thiếu úy quân nhân chuyên nghiệp'),
       ('Thượng sĩ'),
       ('Trung sĩ'),
       ('Hạ sĩ'),
       ('Binh nhất'),
       ('Binh nhì');
--ngach/chuc_danh_nghe_nghiep_cong_chuc
INSERT INTO ngach_cong_chuc (ma, name, he_so_luong_cong_chuc_id)
VALUES ('01.001', 'Chuyên viên cao cấp', 1),
       ('04.023', 'Thanh tra viên cao cấp', 1),
       ('06.029', 'Kế toán viên cao cấp', 1),
       ('06.036', 'Kiểm tra viên cao cấp thuế', 1),
       ('08.049', 'Kiểm tra viên cao cấp hải quan', 2),
       ('07.044', 'Kiểm soát viên cao cấp ngân hàng', 2),
       ('06.041', 'Kiểm toán viên cao cấp', 2),
       ('03.299', 'Chấp hành viên cao cấp', 2),
       ('03.230', 'Thẩm tra viên cao cấp', 2),
       ('21.187', 'Kiểm soát viên cao cấp thị trường', 2),
       ('01.002', 'Chuyên viên chính', 2),
       ('04.024', 'Thanh tra viên chính', 3),
       ('06.030', 'Kế toán viên chính', 3),
       ('06.037', 'Kiểm tra viên chính thuế', 3),
       ('08.050', 'Kiểm tra viên chính hải quan', 3),
       ('19.220', 'Kỹ thuật viên bảo quản chính', 4),
       ('07.045', 'Kiểm soát viên chính ngân hàng', 4),
       ('06.042', 'Kiểm toán viên chính', 4),
       ('03.300', 'Chấp hành viên trung cấp', 5),
       ('03.231', 'Thẩm tra viên chính', 5),
       ('21.188', 'Kiểm soát viên chính thị trường', 5),
       ('09.315', 'Kiểm dịch viên chính động vật', 5),
       ('09.318', 'Kiểm dịch viên chính thực vật', 6),
       ('11.081', 'Kiểm soát viên chính đê điều', 6),
       ('10.225', 'Kiểm lâm viên chính', 6),
       ('25.309', 'Kiểm ngư viên chính', 7),
       ('25.312', 'Thuyền viên kiểm ngư chính', 7),
       ('02.006', 'Văn thư chính', 7),
       ('01.003', 'Chuyên viên', 8),
       ('04.025', 'Thanh tra viên', 8),
       ('06.031', 'Kế toán viên', 8),
       ('06.038', 'Kiểm tra viên thuế', 9),
       ('08.051', 'Kiểm tra viên hải quan', 9),
       ('19.221', 'Kỹ thuật viên bảo quản', 9),
       ('07.046', 'Kiểm soát viên ngân hàng', 10),
       ('06.043', 'Kiểm toán viên', 10),
       ('03.301', 'Chấp hành viên sơ cấp', 10),
       ('03.232', 'Thẩm tra viên', 10),
       ('03.302', 'Thư ký thi hành án', 11),
       ('21.189', 'Kiểm soát viên thị trường', 11),
       ('09.316', 'Kiểm dịch viên động vật', 11),
       ('09.319', 'Kiểm dịch viên thực vật', 11),
       ('11.082', 'Kiểm soát viên đê điều', 11),
       ('10.226', 'Kiểm lâm viên', 12),
       ('25.310', 'Kiểm ngư viên', 12),
       ('25.313', 'Thuyền viên kiểm ngư', 12),
       ('02.007', 'Văn thư', 12),
       ('01.004', 'Cán sự', 12),
       ('06.032', 'Kế toán viên trung cấp', 9),
       ('06.039', 'Kiểm tra viên trung cấp thuế', 5),
       ('08.052', 'Kiểm tra viên trung cấp hải quan', 1),
       ('21.190', 'Kiểm soát viên trung cấp thị trường', 2),
       ('19.222', 'Kỹ thuật viên bảo quản trung cấp', 3),
       ('19.223', 'Thủ kho bảo quản', 4),
       ('01.005', 'Nhân viên (văn thư, bảo vệ, lái xe, phục vụ, lễ tân, kỹ thuật và các nhiệm vụ khác…)', 5),
       ('06.040', 'Nhân viên thuế', 5),
       ('08.053', 'Nhân viên hải quan', 7),
       ('07.048', 'Thủ kho ngân hàng', 8),
       ('06.034', 'Thủ quỹ ngân hàng', 5),
       ('07.047', 'Kiểm ngân', 1),
       ('03.303', 'Thư ký trung cấp thi hành án', 2),
       ('09.317', 'Kỹ thuật viên kiểm dịch động vật', 3),
       ('09.320', 'Kỹ thuật viên kiểm dịch thực vật', 4),
       ('11.083', 'Kiểm soát viên trung cấp đê điều', 5),
       ('10.228', 'Kiểm lâm viên trung cấp', 6),
       ('25.311', 'Kiểm ngư viên trung cấp', 7),
       ('25.314', 'Thuyền viên kiểm ngư trung cấp', 8),
       ('02.008', 'Văn thư trung cấp', 9),
       ('06.035', 'Thủ quỹ cơ quan, đơn vị', 10),
       ('19.186', 'Bảo vệ, tuần tra canh gác', 15),
       ('19.224', 'Nhân viên bảo vệ kho dự trữ (Công chức loại C1)', 12);
--ngach/chuc_danh_nghe_nghiep vien chuc
INSERT INTO ngach_vien_chuc (ma, name, he_so_luong_vien_chuc_id)
values ('V.07.01.01', 'Giảng viên cao cấp (hạng I)', 1),
       ('V.07.08.20', 'Giảng viên cao đẳng sư phạm cao cấp (hạng I)', 1),
       ('V.09.02.01', 'Giảng viên giáo dục nghề nghiệp cao cấp (hạng I)', 1),
       ('V.09.02.05', 'Giáo viên giáo dục nghề nghiệp hạng I', 1),
       ('V.08.01.01', 'Bác sĩ cao cấp (hạng I)', 1),
       ('V.08.02.04', 'Bác sĩ y học dự phòng cao cấp (hạng I)', 1),
       ('V.08.08.20', 'Dược sĩ cao cấp (hạng I)', 1),
       ('V.08.04.08', 'Y tế công cộng cao cấp (hạng I)', 1),
       ('V.10.03.08', 'Đạo diễn nghệ thuật hạng I', 1),
       ('V.10.04.12', 'Diễn viên hạng I', 1),
       ('V.10.01.01', 'Huấn luyện viên cao cấp (Hạng I)', 1),
       ('V.05.01.01', 'Nghiên cứu viên cao cấp (Hạng I)', 1),
       ('V.05.02.05', 'Kỹ sư cao cấp (Hạng I)', 1),
       ('V11.09.23', 'Âm thanh viên hạng I', 1),
       ('V11.10.27', 'Phát thanh viên hạng I', 1),
       ('V11.11.31', 'Kỹ thuật dựng phim hạng I', 1),
       ('V11.12.35', 'Quay phim hạng I', 1),
       ('V.11.01.01', 'Biên tập viên hạng I', 1),
       ('V.11.02.04', 'Phóng viên hạng I', 1),
       ('V.11.03.07', 'Biên dịch viên hạng I', 1),
       ('V.11.04.10', 'Đạo diễn truyền hình hạng I', 1),
       ('V.04.01.01', 'Kiến trúc sư Hạng I', 1),
       ('V.04.02.04', 'Thẩm kế viên hạng I', 1),
       ('V.10.08.25', 'Họa sĩ hạng I', 1),
       ('V.07.01.02', 'Giảng viên chính (hạng II)', 1),
       ('V.07.07.17', 'Giáo viên dự bị đại học hạng I', 1),
       ('V.07.07.18', 'Giáo viên dự bị đại học hạng II', 1),
       ('V.07.08.21', 'Giảng viên cao đẳng sư phạm cao cấp (hạng II)', 1),
       ('V.09.02.02', 'Giảng viên giáo dục nghề nghiệp chính (hạng II)', 1),
       ('V.09.02.06', 'Giáo viên giáo dục nghề nghiệp hạng II', 1),
       ('V.07.05.13', 'Giáo viên trung học phổ thông (hạng I)', 1),
       ('V.07.05.14', 'Giáo viên trung học phổ thông (hạng II)', 1),
       ('V.07.04.30', 'Giáo viên trung học cơ sở hạng I', 1),
       ('V.07.04.31', 'Giáo viên trung học cơ sở hạng II', 1),
       ('V.07.03.27', 'Giáo viên tiểu học hạng I', 1),
       ('V.07.03.28', 'Giáo viên tiểu học hạng II', 1),
       ('V.07.02.24', 'Giáo viên mầm non hạng I', 1),
       ('V.08.02.05', 'Bác sĩ y học dự phòng chính (hạng II)', 1),
       ('V.08.01.02', 'Bác sĩ chính (hạng II)', 1),
       ('V.08.08.21', 'Dược sĩ chính (hạng II)', 1),
       ('V.08.05.11', 'Điều dưỡng hạng II', 1),
       ('V.08.06.14', 'Hộ sinh hạng II', 1),
       ('V.08.07.17', 'Kỹ thuật y hạng II', 1),
       ('V.08.04.09', 'Y tế công cộng chính (hạng II)', 1),
       ('V.09.03.01', 'Kiểm định viên chính kỹ thuật an toàn lao động (hạng II)', 1),
       ('V.09.04.01', 'Công tác xã hội viên chính (hạng II)', 1),
       ('V.10.03.09', 'Đạo diễn nghệ thuật hạng II', 1),
       ('V.10.04.13', 'Diễn viên hạng II', 1),
       ('V.10.05.16', 'Di sản viên hạng II', 1),
       ('V.10.01.02', 'Huấn luyện viên chính (hạng II)', 1),
       ('V.05.01.02', 'Nghiên cứu viên chính (Hạng II)', 1),
       ('V.05.02.06', 'Kỹ sư chính (Hạng II)', 1);
-- moi_quan_he
INSERT into moi_quan_he (name)
VALUES ('Mẹ ruột'),
       ('Mẹ nuôi'),
       ('Ba ruột'),
       ('Ba nuôi'),
       ('Anh ruột'),
       ('Anh nuôi'),
       ('Chị ruột'),
       ('Chị nuôi'),
       ('Em nuôi'),
       ('Em ruột'),
       ('Vợ'),
       ('Con ruột'),
       ('Con nuôi');
-- loai_phu_cap
INSERT into loai_phu_cap (name)
VALUES ('Phụ cấp kiêm nhiệm'),
       ('Phụ cấp thâm niên vượt khung'),
       ('Phụ cấp khu vực'),
       ('Phụ cấp trách nhiệm công việc'),
       ('Phụ cấp lưu động'),
       ('Phụ cấp phục vụ an ninh, quốc phòng'),
       ('Phụ cấp đặc thù đối với lực lượng vũ trang');
-- vi_tri_viec_lam
INSERT into vi_tri_viec_lam (name, bac_luong_id, tien_luong)
VALUES ('Giám đốc', 6, 9000000),
       ('Thư ký', 4, 6000000),
       ('Thù kho', 2, 3000000),
       ('Phó giám đốc', 5, 7000000);