server:
  port: 8079
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs

spring:
  profiles:
    default: auth-token
    active: auth-token
  application:
    name: auth-token
  config:
    import: optional:configserver:http://localhost:1111
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #this eureka need to register itself so set true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka