server:
  port: 8888
  servlet:
    context-path: /api/v1

spring:
  profiles:
    default: gateaway
  application:
    name: gateaway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: false
