server:
  port: 8003
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: ho-so #name application in eureka
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ho_so?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: never

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #this eureka client need to register discovery so set true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

moduleUrl:
  ho-so-chi-tiet: http://localhost:8004/api/v1
  cau-hinh: http://localhost:8001/api/v1