server:
  port: 8082
  servlet:
    context-path: /api/v1

springdoc:
  api-docs:
    path: /api-docs

spring:
  application:
    name: tai-khoan #name application in eureka
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tai_khoan?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
  mail: #send main
    host: smtp.gmail.com
    port: 587
    username: hentaiktvn321@gmail.com
    password: kshjuungovoianlv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
        starttls:
          enable: true

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true #this eureka doesn't need to register itself so set false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    org:
      springframework:
        security: debug

moduleUrl:
  auth-token: http://localhost:8079/api/v1
  ho-so: http://localhost:8081/api/v1
  ho-so-chi-tiet: http://localhost:8083/api/v1


