spring:
  profiles:
    default: discovery
    active: discovery
  application:
    name: discovery
  config: #because i have config server, so i want this eureka server read configuration from config server.
    import: optional:configserver:http://localhost:1111



