spring:
  profiles:
    default: hoso
  application: #this must same name at yml file in config-server
    name: ho-so #name application in eureka
  config:
    import: optional:configserver:http://localhost:1111
