spring:
  application: #this must same name at yml file in config-server
    name: ho-so #name application in eureka
  config:
    import: optional:configserver:http://localhost:1111

gateway-port:
  ho-so: https://8888-giaptai-microservicehrm-neez1b8nx7s.ws-us110.gitpod.io/api/v1
